# Generated by Django 5.2.8 on 2025-11-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('os', models.CharField(max_length=255, verbose_name='操作系统')),
                ('cpu', models.IntegerField(verbose_name='CPU核数')),
                ('memory', models.IntegerField(verbose_name='内存大小')),
                ('disk', models.IntegerField(verbose_name='磁盘大小')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
        ),
    ]
